version: '3.5'

services:
  back:
    image: back:latest
    networks: 
      - backend
  front:
    image: front:latest
    ports:
      - "8001:5000"
    links:
      - back
    networks: 
      - backend

networks:
  backend:
    driver: bridge

