apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: flaskapi
  name: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flaskapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: flaskapi
    spec:
      containers:
        - image: flaskapi:latest
          name: flaskapi
          resources: {}
      restartPolicy: Always
status: {}
