apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
       - image: gcr.io/total-zodiac-335107/front
         imagePullPolicy: Always
         name: front
         ports:
           - containerPort: 5000
