apiVersion: v1
kind: Pod
metadata:
  name: front
  labels:
    app: front
spec:
  containers:
    - image: gcr.io/total-zodiac-335107/front
      name: front
      ports:
        - containerPort: 5000
