name: Deploy simple hello app to GKE

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: github-actions-339911
  GKE_CLUSTER: cluster-1    # TODO: update to cluster name
  GKE_ZONE: europe-north1-a	   # TODO: update to cluster zone
  DEPLOYMENT_NAME: back # TODO: update deployment name if changed in deployment.yaml

jobs:
  zzz:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/321169889619/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider'
        service_account: 'gha-service-acc@github-actions-339911.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: 'cluster-1'
        location: 'europe-north1-a'

    # The KUBECONFIG env var is automatically exported and picked up by kubectl.
    - id: 'get-pods'
      run: 'kubectl get pods'        

